### ISSUE TITLE
Discord Bot for Extension Updates

### ISSUE THREAD

**Issue by itsmechinmoy** [kaorlol/obtainium-helper#1]
Make a Discord bot that edits existing webhook messages instead of sending new ones when a new extension update is available. The title of the webhook could be the name of the extension, such as "New YouTube Update," followed by the commits and APK. The footer will display the last updated time.

The number of webhooks will correspond to the number of extensions. Each time there is an update for a particular extension, the bot will ping the relevant role.

> Just a suggestion, I don't even know if you know how to make a Discord bot

**Comment by kaorlol** [comment]
Added webhook support.
